# -*- coding: utf-8 -*-
"""lab5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BafPWhNT1HF6GSAGs-eehBKs8FKpkTd3
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv('animalSensorReadings.csv')
df = df.sort_values(['animal', 'timestamp'], ascending=[True, True])

import numpy as np
import matplotlib.pyplot as plt

def calculate_and_plot(in_df, zebra):
  df_speed = in_df[['locationX', 'locationY', 'timestamp']]
  dist = df_speed.diff().fillna(0)
  dist['dist'] = np.sqrt(dist.locationX**2 + dist.locationY**2)
  dist['speed'] = dist.dist/dist.timestamp
  x = np.sort(dist['speed'])
  #y = np.arange(1, len(x)+1/len(x))
  N = len(x)
  y = np.arange(N) / float(N)

  _ = plt.plot(x, y, marker='.',linestyle='none')
  _ = plt.xlabel('speed of zebras')
  _ = plt.ylabel("CDF")
  plt.margins(0.02)

for zebra in df.animal.unique():
  
  df_zebra = df[df['animal'] == zebra]
  calculate_and_plot(df_zebra, zebra)
plt.show()

df.animal.unique()

def scatter_plot(x, y, color):
  plt.scatter(x, y,  c=color)

scatter_plot(df.locationX, df.locationY, df.animal)
plt.show()